### ISSUE TITLE
Does the startree pinot suiperset image have superset code changes that are not merged back to superset?

### ISSUE THREAD

**Issue by ghost** [Barkha/apache-pinot-workshops#3]
@Barkha I tried to connect an existing apache superset installation to pinot db and get an error when creating a dataset. I see now that the tutorial for using pinot with superset all seem to use the startree superset image. Is there a repo that I can view the code changes that have been made to the startree superset image code?

**Comment by ghost** [comment]
@Barkha Any thoughts on this?

**Comment by Barkha** [comment]
Apologies for the delayes response.  If you check the docker compose file, you will see tht the image is publicly available, and has the built in pinot connector in it.
